apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: ai-task-platform
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: redclubx/ai-task-worker:d0809514dfec1c28f9ecd0f18e4474653cf9495b
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import redis; r = redis.Redis(host='redis', port=6379); r.ping()"
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import redis; r = redis.Redis(host='redis', port=6379); r.ping()"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
