apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayush24kr/Assignment.git
    targetRevision: main
    path: infra/base
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
